CREATE TABLE IF NOT EXISTS `settings` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `config_key` VARCHAR(191) NOT NULL UNIQUE,
  `config_value` TEXT NOT NULL,
  `group` VARCHAR(100) NOT NULL DEFAULT 'general',
  `description` TEXT NULL,
  `is_protected` TINYINT(1) NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
